### ISSUE TITLE
Implementar relatório de situação

### ISSUE THREAD

**Issue by r1cardvs** [Javali-FATEC/API-2-semestre#25]
Deve ser possível selecionar uma cidade. O relatório deve apresentar as média das ultimas medições feitas para cada variável climática daquela determinada cidade.

**Comment by c137santos** [comment]
Primeiro, precisa partir da tela master, onde precisa ser feito o botão para o relatório


![Image](https://github.com/Javali-FATEC/API-2-semestre/assets/92645535/81ea25b3-a9f2-4e73-ac58-076fec2e8f9a)

**Comment by c137santos** [comment]
Por último, gerar
Frontend GRID
Backend preencher variáveis do Grid com a média

![Image](https://github.com/Javali-FATEC/API-2-semestre/assets/92645535/12a25663-cf39-4e9d-83ac-d97b9a5a5c0f)

**Comment by r1cardvs** [comment]
Para testar esse relatório pode utilizar esse relatório, atribuindo todas as estações presentes a uma mesma cidade e váriavel climática.

[registroTeste.csv](https://github.com/Javali-FATEC/API-2-semestre/files/15165284/registroTeste.csv)

Os valores esperados para o relatório dessa variavel e cidade é 80
