### ISSUE TITLE
#37 Subir o banco com docker e melhora dos scripts do banco

### ISSUE THREAD

**Issue by marilia-borgo** [Javali-FATEC/API-2-semestre#37]
Cria a opção de subir o banco de dados em um docker separado, conserta os scripts pra que rodo corretamente, adiciona informações pra a criação do banco no settings.

**Comment by c137santos** [comment]
Adicionei uma complementação NO PR do Isaac.

**Comment by c137santos** [comment]
https://github.com/Javali-FATEC/API-2-semestre/pull/38
