### ISSUE TITLE
RELATORIO_BOXPLOT: Classe calculo dos quartis.

### ISSUE THREAD

**Issue by marilia-borgo** [Javali-FATEC/API-2-semestre#62]
User storie:

- Quatil 1: Valor que está posição de 25% do tamanho conjunto analisado. - Mediana (Quatil 2): Valor que está posição de 50% do tamanho conjunto analisado. - Quatil 3: Valor que está posição que equivale 75% do tamanho conjunto analisado. Esse relatório deve ser gerado a partir da seleção de uma estação e uma data específica. Não se deve listar todas as estações, deve ser selecionada uma cidade e assim disponibilizar as estações para seleção do usuário.

Entregável:

Classe quartil, com três atributos (quartil1 , quartil2, e quartil3), que deverá ser usada para a criação do gráfico boxplot.A classe deve receber como parâmetros data, cidade, estação e tipo de dado.

**Comment by r1cardvs** [comment]
Segue formula para calculo dos Quartis:

![Image](https://github.com/Javali-FATEC/API-2-semestre/assets/70415796/47a9823f-38a4-47c9-807a-5d2130a9d031)

Onde n é o numero total de elementos.

Obs: o Quartil 2 é a mediana.
