### ISSUE TITLE
Bugfix - Relatório de situação

### ISSUE THREAD

**Issue by PalomaSoaresR** [Javali-FATEC/API-2-semestre#71]

**Comment by c137santos** [comment]
Olar, me dá a task que eu conclui https://github.com/Javali-FATEC/API-2-semestre/pull/72/files

**Comment by r1cardvs** [comment]
Para testes:
Utilize os inserts a seguir:
`-- Inserir as estações com IDs arbitrários
INSERT INTO estacao (id_estacao, nome_estacao)
VALUES (1, 'A771'), (2, 'B452'), (3, 'C123');

-- Inserir as métricas com IDs arbitrários
INSERT INTO metrica (id_metrica, nome_metrica)
VALUES (1, 'Valor');

-- Inserir os registros do CSV na tabela registro
INSERT INTO registro (id_metrica, id_estacao, valor, data_hora)
VALUES
    (1, 1, 95, '2024-04-30 08:00:00'),
    (1, 2, 75, '2024-04-30 08:00:00'),
    (1, 3, 85, '2024-04-30 08:00:00'),
    (1, 1, 80, '2024-04-30 10:00:00'),
    (1, 2, 95, '2024-04-30 10:00:00'),
    (1, 3, 75, '2024-04-30 10:00:00'),
    (1, 1, 85, '2024-04-30 12:00:00'),
    (1, 2, 95, '2024-04-30 12:00:00'),
    (1, 3, 80, '2024-04-30 12:00:00'),
    (1, 1, 75, '2024-04-30 14:00:00'),
    (1, 2, 85, '2024-04-30 14:00:00'),
    (1, 3, 95, '2024-04-30 14:00:00'),
    (1, 1, 80, '2024-04-30 16:00:00'),
    (1, 2, 75, '2024-04-30 16:00:00'),
    (1, 3, 85, '2024-04-30 16:00:00'),
    (1, 1, 95, '2024-05-01 08:00:00'),
    (1, 2, 75, '2024-05-01 08:00:00'),
    (1, 3, 85, '2024-05-01 08:00:00'),
    (1, 1, 80, '2024-05-01 10:00:00'),
    (1, 2, 95, '2024-05-01 10:00:00'),
    (1, 3, 75, '2024-05-01 10:00:00'),
    (1, 1, 85, '2024-05-01 12:00:00'),
    (1, 2, 95, '2024-05-01 12:00:00'),
    (1, 3, 80, '2024-05-01 12:00:00'),
    (1, 1, 75, '2024-05-01 14:00:00'),
    (1, 2, 85, '2024-05-01 14:00:00'),
    (1, 3, 95, '2024-05-01 14:00:00'),
    (1, 1, 80, '2024-05-01 16:00:00'),
    (1, 2, 75, '2024-05-01 16:00:00'),
    (1, 3, 85, '2024-05-01 16:00:00'),
    (1, 1, 95, '2024-05-02 08:00:00'),
    (1, 2, 75, '2024-05-02 08:00:00'),
    (1, 3, 85, '2024-05-02 08:00:00'),
    (1, 1, 80, '2024-05-02 10:00:00'),
    (1, 2, 95, '2024-05-02 10:00:00'),
    (1, 3, 75, '2024-05-02 10:00:00'),
    (1, 1, 85, '2024-05-02 12:00:00'),
    (1, 2, 95, '2024-05-02 12:00:00'),
    (1, 3, 80, '2024-05-02 12:00:00'),
    (1, 1, 75, '2024-05-02 14:00:00'),
    (1, 2, 85, '2024-05-02 14:00:00'),
    (1, 3, 95, '2024-05-02 14:00:00'),
    (1, 1, 80, '2024-05-02 16:00:00'),
    (1, 2, 75, '2024-05-02 16:00:00'),
    (1, 3, 85, '2024-05-02 16:00:00');
`

Os valores gerados para a metrica hipotetica "Valor" que tem id 1, deve gerar o seguinte resultado:

Valor: 80 na Estação A771
Valor: 75 na Estação B452
Valor: 85 na Estação C123

Sendo a média desses valores 80, ou seja, seria esse o valor desejado no relatório ao considerar esses registros. 

Obs: Os valores por estação foram mencionados apenas para melhor entendimento no caso o retorno do relatório é apenas o valor 80.
