### ISSUE TITLE
RELATÓRIO DE SITUÇÃO: O relatório deve exibir também as unidades envolvidas.

### ISSUE THREAD

**Issue by r1cardvs** [Javali-FATEC/API-2-semestre#74]
Atualmente o relatório de situação está retornando ao usuário somente duas colunas, são essas:
Média dos Valores e a Variavel Climática/Métrica envolvida. Falta informar também a unidade do valor, por exemplo:

Retorno atual:
Valor: 30 | Variável Climática/Métrica: Temperatura

Retorno desejado:
Valor: 30**ºC** | Variável Climática/Métrica: Temperatura

**Comment by c137santos** [comment]
Me bota que eu sou PJ.
